replicaCount: 1

image:
  repository: gantagouthamyadav/inference-api
  tag: "your-latest-tag"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
# test
