apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-tracking
  namespace: mlflow
  labels:
    app: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow
          image: ghcr.io/mlflow/mlflow:v2.13.0
          ports:
            - containerPort: 5000
          env:
            - name: MLFLOW_S3_ENDPOINT_URL
              value: https://s3.us-east-2.amazonaws.com
            - name: AWS_REGION
              value: us-east-2
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: mlflow-aws-creds
                  key: accessKeyID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: mlflow-aws-creds
                  key: secretAccessKey
          args:
            - mlflow
            - server
            - --backend-store-uri
            - sqlite:///mlflow.db
            - --default-artifact-root
            - s3://mlops-anomaly-dev-mlflow-artifacts
            - --host
            - 0.0.0.0
