apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inference-service
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/gouthamyadavganta/mlops-anomaly-detection
    targetRevision: HEAD
    path: helm/inference-api

  destination:
    server: https://kubernetes.default.svc
    namespace: inference

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
