apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-inference
spec:
  selector:
    app: inference
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8000
