name: Build & Deploy Inference Service

on:
  push:
    paths:
      - 'services/inference-api/**'
      - 'helm/inference-api/**'
  workflow_dispatch:

jobs:
  build-and-pr:
    runs-on: ubuntu-latest

    env:
      IMAGE_REPO: gantagouthamyadav/inference-api

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set image tag to short SHA
      id: vars
      run: echo "TAG_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./services/inference-api
        push: true
        tags: ${{ env.IMAGE_REPO }}:${{ env.TAG_SHA }}

    - name: Update image tag in Helm values.yaml
      run: |
        sed -i "s/tag: .*/tag: \"${TAG_SHA}\"/" helm/inference-api/values.yaml

    - name: Fetch latest main and create/switch to new branch
      run: |
        git fetch origin main
        git checkout origin/main
        git checkout -b auto/update-image-tag

    - name: Create Pull Request for updated values.yaml
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GH_PAT }}  
        commit-message: "Auto: update model image tag"
        title: "Auto PR: Update image tag in Helm chart"
        body: |
          This PR updates the Docker image tag after retraining the model.
        branch: auto/update-image-tag
        base: main
        add-paths: |
          helm/inference-api/values.yaml
