name: Build & Deploy Inference Service

on:
  push:
    paths:
      - 'services/inference-api/**'
      - 'helm/inference-api/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_REPO: gantagouthamyadav/inference-api
      IMAGE_TAG: latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./services/inference-api
        push: true
        tags: ${{ env.IMAGE_REPO }}:${{ env.IMAGE_TAG }}

    - name: Trigger ArgoCD auto-sync (optional)
      run: echo "If ArgoCD is configured for auto-sync, this step is not required."

