name: Train Model

on:
  workflow_dispatch:
  push:
    paths:
      - 'model/**'

jobs:
  train:
    runs-on: ubuntu-latest

    env:
      MLFLOW_TRACKING_URI: http://aef27c7c07e634833bf412c822a538fe-2121813122.us-east-2.elb.amazonaws.com:5000
      MLFLOW_S3_ENDPOINT_URL: https://s3.us-east-2.amazonaws.com
      AWS_DEFAULT_REGION: us-east-2

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r model/requirements.txt

    - name: Train model and log to MLflow
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        cd model/scripts
        python train.py

    - name: Upload trained model (model.pkl)
      uses: actions/upload-artifact@v4
      with:
        name: model-pkl
        path: model/scripts/model.pkl

    - name: Download model artifact to inference service directory
      uses: actions/download-artifact@v4
      with:
        name: model-pkl
        path: services/inference-api/

    - name: Debug: Echo Repo and Token Length
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        echo "Repo: https://github.com/gouthamyadavganta/mlops-anomaly-detection.git"
        echo "Token Length: ${#GH_PAT}"

    - name: Debug: Show Git Remote
      run: git remote -v

    - name: Commit and push updated model.pkl
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add services/inference-api/model.pkl
        git commit -m "Auto: update model.pkl after retraining" || echo "No changes to commit"
        git remote set-url origin https://x-access-token:${GH_PAT}@github.com/gouthamyadavganta/mlops-anomaly-detection.git
        git push origin HEAD:main

