name: Train Model

on:
  workflow_dispatch:
  push:
    paths:
      - 'model/**'

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r model/requirements.txt

    - name: Train model
      run: |
        cd model/scripts
        python train.py

    - name: Upload trained model (model.pkl)
      uses: actions/upload-artifact@v4
      with:
        name: model-pkl
        path: model/scripts/model.pkl
